services:
  app:
    build: ./app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql2://root:password@db:3306/codetest

  db:
    image: mysql:8.0
    ports:
      - "3306:3306" # Required for go test to reach the DB from WSL
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=codetest
