services:
  app:
    build: ./app
    volumes:
      - ./app:/rails-api
    ports:
      - "8080:8080" # Mapping for standard dev server
      - "8888:8080" # Mapping for Test server
    working_dir: /rails-api
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      # - DATABASE_URL=mysql2://root@db:3306/codetest
    command: >
      bash -c "
      echo 'Waiting for database...' &&
      sleep 5 &&
      rails db:prepare RAILS_ENV=test &&
      rm -f tmp/pids/server.pid &&
      bundle exec rails s -p 8080 -b '0.0.0.0'"

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=codetest
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

  tester:
    image: golang:1.23
    volumes:
      - .:/test-dir
    working_dir: /test-dir
    # This maps 'localhost' inside the container to the host machine's 'host-gateway' interface
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=codetest
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PORT=3306
    depends_on:
      db:
        condition: service_healthy
    command: go test

volumes:
  mysql_data:
