services:
  app:
    build: ./app
    volumes:
      - ./app:/rails-api
    ports:
      - "8080:8080" # Mapping for standard dev server
      - "8888:8080" # Mapping for Test server
    working_dir: /rails-api
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=mysql2://root@db:3306/codetest

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=codetest
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  tester:
    image: golang:1.23
    volumes:
      - .:/test-dir
    working_dir: /test-dir
    # This maps 'localhost' inside the container to the host machine's 'host-gateway' interface
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=codetest
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PORT=3306
    depends_on:
      db:
        condition: service_healthy
    command: go test

volumes:
  mysql_data:
